### ISSUE TITLE
Connect the pipeline to the GitHub repository

### ISSUE THREAD

**Issue by cgrillo1** [nyu-devops-shopcarts/shopcarts#109]
**As a** Developer
**I need** To connect this pipeline to the GitHub repo via webhook
**So that** I can automatically run my pipeline when a commit is pushed to the repo

**Assumptions :**
* Everyone must have Master or Owner privileges to use webhooks

**Acceptance Criteria:**
```
Given a commit is pushed to the repo,
When I have webhooks installed,
Then my pipeline will run automatically
```

**Comment by NVijapura** [comment]
![image](https://user-images.githubusercontent.com/61212603/80815076-9e90d780-8b92-11ea-90b4-759a6d84e9b0.png)


Test:
Go to https://cloud.ibm.com/resources
Check the resource is configured

![image](https://user-images.githubusercontent.com/61212603/80815179-c41de100-8b92-11ea-98b2-de87d353ab8d.png)

**Comment by cgrillo1** [comment]
Looks good, made sure the entire team is an authorized user and good to go!
