### ISSUE TITLE
Ensure code conforms to PEP8 Python

### ISSUE THREAD

**Issue by robertung88** [nyu-devops-shopcarts/shopcarts#14]
**As a** developer
**I need** to ensure that my code conforms to PEP8 Python standard
**So that** we're aligned with coding standards

**Assumptions :**
* We use PyLint as shown in class
* We run PyLint as we code or when we finish coding to ensure that everything is up to standard. If not we need to make the required adjustments to our code.

**Acceptance Criteria:**
> Your pylint score must be at least 9.0/10.0.

Given ...
When ...
Then ...
```

**Comment by cgrillo1** [comment]
Not an issue itself, rather make sure all issues comply -more of an acceptance criteria
