### ISSUE TITLE
Create Travis CI Account

### ISSUE THREAD

**Issue by NVijapura** [nyu-devops-shopcarts/shopcarts#53]
**As a**  developer
**I need** a continuous integration account on Travis
**So that** we can connect the CI account with the GitHub Organization.

**Assumptions:**
* Travis CI website is still operational

**Acceptance Criteria:**
The team is able to log into the account

Given ... my travis CI account is integrated with the github organization
When ... I make a pull request
Then ... travis should automatically run the appropriate test cases
```

**Comment by NVijapura** [comment]
I think this was completed at : https://travis-ci.org/github/nyu-devops-shopcarts/shopcarts


We should all be able to login to Travis and see the page. This is what I see right now:
![image](https://user-images.githubusercontent.com/61212603/78390622-d9fbae80-75b2-11ea-9117-ddd61f0c734b.png)

**Comment by alssetton** [comment]
This created an empty Travis account.
