### ISSUE TITLE
Consolidate team members into IBM Cloud Organization

### ISSUE THREAD

**Issue by pjfolino** [nyu-devops-shopcarts/shopcarts#55]
**As a** development team
**I need** access to the IBM cloud organization
**So that** I can work with the dev team to deploy a microservice to the cloud.

**Assumptions :**
* Professor to provide instructions on how to invite members to the IBM cloud organization.

**Acceptance Criteria:**
```

Given I have completed the prerequisite issues and user stories
When I press `ibmcloud cf push`
Then my microservice should deploy to IBM cloud.
```

**Comment by cgrillo1** [comment]
This has been set up in IBM cloud account already

**Comment by NVijapura** [comment]
All users have been added to the IBM Cloud Account
