### ISSUE TITLE
Create a Python Flask Cloud Foudry application in IBM Cloud

### ISSUE THREAD

**Issue by pjfolino** [nyu-devops-shopcarts/shopcarts#56]
**As a** developer
**I need** a Python Flask Cloud Foundry Application
**So that**  I can quickly and easily build, test, deploy and scale the shopcarts microservice.

**Assumptions :**
* We will use IBM as the cloud provider

**Acceptance Criteria:**
```

Given the shopcarts microservice passes build tests of Travis CI,
When I type `ibmcloud cf push` into the command line,
Then my microservice will launch to the cloud.
```

**Comment by cgrillo1** [comment]
Two cloud foundry apps in IBM cloud account
