### ISSUE TITLE
Update Vagrantfile to download and install IBM Cloud CLI

### ISSUE THREAD

**Issue by pjfolino** [nyu-devops-shopcarts/shopcarts#58]
**As a**  developer,
**I need** an up to date Vagrantfile to download and install IBM Cloud 
**So that** I can make commands in the command-line and have a standard environment with the rest of the dev team.

**Assumptions :**
* Will need to establish a Bluemix and Kubernetes environment
* Will use couchDB for docker container
* vm.hostname = "ibmcloud"

**Acceptance Criteria:**
```

Given I have updated my Vagrantfile with IBM Cloud CLI
When I change directory into the Virtual Machine
Then I should see `ibmcloud` as hostname
```

**Comment by NVijapura** [comment]
![image](https://user-images.githubusercontent.com/61212603/78942324-79bfad80-7a87-11ea-8f5c-083aa0f16e56.png)


Was able to update the vagrantfile and log into the account. 


Note: Every user must have their own apikey and store it locally at "~/.bluemix/apiKey-team.json". Follow the instructions in 07-PlatformAsAService.pdf starting on Page 6. The only difference is to select her account right after you login.

Code to login: 
ibmcloud login -a https://cloud.ibm.com --apikey @~/.bluemix/apiKey-team.json -r us-south -o cmg509@stern.nyu.edu -s dev
