### ISSUE TITLE
Add [QUERY] scenario to feature file

### ISSUE THREAD

**Issue by alssetton** [nyu-devops-shopcarts/shopcarts#90]
As a developer
I need a QUERY scenario in the feature file
So that I can use Behave to test my code

Assumptions :

... GHERKIN format is used
... using the red/green/refractor loop
Acceptance Criteria:

Given I have updated the .features file with the QUERY scenario
When I execute on behave
Then the behave tool will pass the QUERY scenario

**Comment by robertung88** [comment]
Not working anymore because we need to do it using the "new" way with copy & pasting. Adjustments to be made in the feature file.
